### ISSUE TITLE
Error message is wrong when user try to use a python version below 3.10

### ISSUE THREAD

**Issue by andre-senna** [singnet/das#62]
Saulo reports this message when trying to use DAS 0.2.0 using python 3.9

![Image](https://github.com/user-attachments/assets/dcfeb420-7b18-4ef2-bd57-b38fbd8fa5ae)

This message doesn't make clear what's really going on. We should provide a proper error message explaining what's the minimal python version we require to run the library.

**Comment by angeloprobst** [comment]
@andre-senna  is there any related doc that should be updated?

**Comment by andre-senna** [comment]
Nope
