### ISSUE TITLE
Connecting to server error

### ISSUE THREAD

**Issue by andre-senna** [singnet/das#66]
I've loaded a MeTTa file into a local DAS, but my Python script is not able to connect to the DAS server.
Steps I did:
1. das-cli db start
2. das-cli faas start
3. das-cli metta load my_file.metta

The script is only:

from hyperon_das import DistributedAtomSpace

host = '127.0.0.1'
port = '8080'
das = DistributedAtomSpace(query_engine='remote', host=host, port=port)

And the error message is:

Traceback (most recent call last):
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/decorators.py", line 21, in wrapper
    status, response = function(args, *kwargs)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/utils.py", line 172, in connect_to_server
    raise Exception(message)
Exception: Error unpickling objects in peer's response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/bio2.py", line 9, in <module>
    das = DistributedAtomSpace(query_engine='remote', host=host, port=port)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/das.py", line 75, in init
    self.set_query_engine(**kwargs)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/das.py", line 109, in set_query_engine
    self.query_engine = RemoteQueryEngine(self.backend, self.system_parameters, kwargs)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/query_engines/remote_query_engine.py", line 29, in __init
    self.remote_das = FunctionsClient(self.host, self.port)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/client.py", line 24, in init
    self.url = connect_to_server(host, port)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/decorators.py", line 29, in wrapper
    raise RetryConnectionError(
hyperon_das.exceptions.RetryConnectionError: ('An error occurs while connecting to the server', "Error unpickling objects in peer's response")

**Comment by andre-senna** [comment]
btw I saw the same behavior reported by Saulo when trying to setup a local environment in my ubuntu workstation

**Comment by levisingularity** [comment]
@andre-senna, could you please provide the metta file and the hyperon-das version that was used when this error occurred so I can try to reproduce the error?

**Comment by andre-senna** [comment]
@levisingularity 

I can't reproduce it anymore. I believe it's because I updated openfaas and das-cli to latest versions.

**Comment by andre-senna** [comment]
@sauloapp 

Can you please share the version of das-cli and openfaas function you are having this error?

**Comment by sauloapp** [comment]
@andre-senna 

das-cli: 0.2.21
faas: query-engine 1.12.11

**Comment by sauloapp** [comment]
Name: hyperon-das
Version: 0.8.1

**Comment by levisingularity** [comment]
Hi @sauloapp, I’m encountering an error related to a version mismatch for hyperon-das. The error message is:

```
raise RetryConnectionError(
hyperon_das.exceptions.RetryConnectionError: ('An error occurred while connecting to the server', "Local DAS version 'das: 0.8.0 and atom_db: 0.7.0', DAS server is expecting 'das: 0.7.13 and atom_db: 0.6.12'")
```

I’m currently using the following versions, same as yours:

```
das-cli 0.2.21

query-engine 1.12.11

hyperon-das
  INSTALLED: 0.8.1
  LATEST:    0.8.1
hyperon-das-atomdb
  INSTALLED: 0.7.1
  LATEST:    0.7.1
```

Is the issue exception still happening for you?

**Comment by sauloapp** [comment]
@levisingularity 
Currently there are some colleagues working with a robot vision system on the Bizon machine and they are changing some settings, I think... Look at this:

saulo@dl:/mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data$ das-cli --version
das-cli 0.3.0

saulo@dl:/mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data$ das-cli faas version
[DockerImageNotFoundError] The image trueagi/openfaas:query-engine-latest for the function could not be located in the Docker Hub repository. Please verify the existence of the version or ensure the correct function name is used.

Besides. mongodb is not starting:

saulo@dl:/mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data$ das-cli db start
Starting Redis service...
Redis has started successfully on port 20123 at localhost, operating under the server user saulo.
Starting MongoDB service...

hyperon-das is  the same version as yours.

**Comment by levisingularity** [comment]
@sauloapp, could you try running `das-cli config set` and then testing it again? It might be using a setting from an older version of `das-cli`.

**Comment by sauloapp** [comment]
@levisingularity ,
I did it and it did not work...
das-cli config set
das-cli db start
das-cli metta load /mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/test.metta
das-cli faas start

saulo@dl:/mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data$ python3 bio2.py 
{'das': {'name': 'hyperon-das', 'version': '0.8.0', 'summary': 'Query Engine API for Distributed AtomSpace'}, 'atom_db': {'name': 'hyperon-das-atomdb', 'version': '0.7.0', 'summary': 'Persistence layer for Distributed AtomSpace'}}
Traceback (most recent call last):
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/decorators.py", line 21, in wrapper
    status, response = function(*args, **kwargs)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/utils.py", line 172, in connect_to_server
    raise Exception(message)
Exception: Error unpickling objects in peer's response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data/bio2.py", line 9, in <module>
    das = DistributedAtomSpace(query_engine='remote', host=host, port=port)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/das.py", line 75, in __init__
    self._set_query_engine(**kwargs)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/das.py", line 109, in _set_query_engine
    self.query_engine = RemoteQueryEngine(self.backend, self.system_parameters, kwargs)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/query_engines/remote_query_engine.py", line 29, in __init__
    self.remote_das = FunctionsClient(self.host, self.port)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/client.py", line 24, in __init__
    self.url = connect_to_server(host, port)
  File "/home/saulo/.local/lib/python3.10/site-packages/hyperon_das/decorators.py", line 29, in wrapper
    raise RetryConnectionError(
hyperon_das.exceptions.RetryConnectionError: ('An error occurs while connecting to the server', "Error unpickling objects in peer's response")

bio2.py:
from hyperon_das import DistributedAtomSpace

print(DistributedAtomSpace().about())

host = '127.0.0.1'
port = '8080'
das = DistributedAtomSpace(query_engine='remote', host=host, port=port)

print(f"Connected to DAS at {host}:{port}")
print("(nodes, links) =", das.count_atoms())


test.metta:
(allele FBal0351315)
(allele_symbol (allele FBal0351315) ash1[DeltaSET.Ubi-p63E])
(gene_id (allele FBal0351315) FBgn0005386)
(taxon_id (allele FBal0351315) 7227)
(allele FBal0351468)
(allele_symbol (allele FBal0351468) Top3beta[TKO.GS04238])
(gene_id (allele FBal0351468) FBgn0026015)
(taxon_id (allele FBal0351468) 7227)
(allele FBal0351534)
(allele_symbol (allele FBal0351534) Mef2[UAS.cUa])
(gene_id (allele FBal0351534) FBgn0011656)
(taxon_id (allele FBal0351534) 7227)
(allele FBal0351671)
(allele_symbol (allele FBal0351671) piwi[SL\(HsAGO2\).UASp.Tag:FLAG,Tag:HA])
(gene_id (allele FBal0351671) FBgn0004872)
(taxon_id (allele FBal0351671) 7227)

**Comment by levisingularity** [comment]
@sauloapp even though I'm using the same setup I could not be able to reproduce this issue, can you run `das-cli logs faas` to see what it shows when this exception is thrown?

**Comment by sauloapp** [comment]
It seems that 8080 is being used.... the whole log:

2024/08/05 20:13:15 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/05 20:13:15 Forking: python, arguments: [index.py]
2024/08/05 20:13:15 Started logging: stderr from function.
2024/08/05 20:13:15 Started logging: stdout from function.
2024/08/05 20:13:15 Watchdog mode: http	fprocess: "python index.py"
2024/08/05 20:13:15 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/05 20:13:15 Listening on port: 8080
2024/08/05 20:13:15 Writing lock-file to: /tmp/.lock
2024/08/05 20:13:15 Metrics listening on port: 8081
2024/08/05 20:13:15 stderr: Traceback (most recent call last):
2024/08/05 20:13:15 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/05 20:13:15 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/05 20:13:15 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/05 20:13:15 stderr:     server = _server(app, **kw)
2024/08/05 20:13:15 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/05 20:13:15 stderr:     last_serv = TcpWSGIServer(
2024/08/05 20:13:15 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/05 20:13:15 stderr:     self.bind_server_socket()
2024/08/05 20:13:15 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/05 20:13:15 stderr:     self.bind(sockaddr)
2024/08/05 20:13:15 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/05 20:13:15 stderr:     return self.socket.bind(addr)
2024/08/05 20:13:15 stderr: OSError: [Errno 98] Address in use
2024/08/05 20:13:15 Forked function has terminated: exit status 1
2024/08/05 20:13:16 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/05 20:13:16 Forking: python, arguments: [index.py]
2024/08/05 20:13:16 Started logging: stderr from function.
2024/08/05 20:13:16 Started logging: stdout from function.
2024/08/05 20:13:16 Watchdog mode: http	fprocess: "python index.py"
2024/08/05 20:13:16 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/05 20:13:16 Listening on port: 8080
2024/08/05 20:13:16 Writing lock-file to: /tmp/.lock
2024/08/05 20:13:16 Metrics listening on port: 8081
2024/08/05 20:13:16 stderr: Traceback (most recent call last):
2024/08/05 20:13:16 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/05 20:13:16 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/05 20:13:16 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/05 20:13:16 stderr:     server = _server(app, **kw)
2024/08/05 20:13:16 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/05 20:13:16 stderr:     last_serv = TcpWSGIServer(
2024/08/05 20:13:16 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/05 20:13:16 stderr:     self.bind_server_socket()
2024/08/05 20:13:16 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/05 20:13:16 stderr:     self.bind(sockaddr)
2024/08/05 20:13:16 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/05 20:13:16 stderr:     return self.socket.bind(addr)
2024/08/05 20:13:16 stderr: OSError: [Errno 98] Address in use
2024/08/05 20:13:16 Forked function has terminated: exit status 1
2024/08/05 20:13:16 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/05 20:13:16 Forking: python, arguments: [index.py]
2024/08/05 20:13:16 Started logging: stderr from function.
2024/08/05 20:13:16 Started logging: stdout from function.
2024/08/05 20:13:16 Watchdog mode: http	fprocess: "python index.py"
2024/08/05 20:13:16 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/05 20:13:16 Listening on port: 8080
2024/08/05 20:13:16 Writing lock-file to: /tmp/.lock
2024/08/05 20:13:16 Metrics listening on port: 8081
2024/08/05 20:13:17 stderr: Traceback (most recent call last):
2024/08/05 20:13:17 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/05 20:13:17 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/05 20:13:17 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/05 20:13:17 stderr:     server = _server(app, **kw)
2024/08/05 20:13:17 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/05 20:13:17 stderr:     last_serv = TcpWSGIServer(
2024/08/05 20:13:17 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/05 20:13:17 stderr:     self.bind_server_socket()
2024/08/05 20:13:17 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/05 20:13:17 stderr:     self.bind(sockaddr)
2024/08/05 20:13:17 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/05 20:13:17 stderr:     return self.socket.bind(addr)
2024/08/05 20:13:17 stderr: OSError: [Errno 98] Address in use
2024/08/05 20:13:17 Forked function has terminated: exit status 1
2024/08/05 20:13:17 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/05 20:13:17 Forking: python, arguments: [index.py]
2024/08/05 20:13:17 Started logging: stderr from function.
2024/08/05 20:13:17 Started logging: stdout from function.
2024/08/05 20:13:17 Watchdog mode: http	fprocess: "python index.py"
2024/08/05 20:13:17 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/05 20:13:17 Listening on port: 8080
2024/08/05 20:13:17 Writing lock-file to: /tmp/.lock
2024/08/05 20:13:17 Metrics listening on port: 8081
2024/08/05 20:13:18 stderr: Traceback (most recent call last):
2024/08/05 20:13:18 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/05 20:13:18 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/05 20:13:18 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/05 20:13:18 stderr:     server = _server(app, **kw)
2024/08/05 20:13:18 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/05 20:13:18 stderr:     last_serv = TcpWSGIServer(
2024/08/05 20:13:18 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/05 20:13:18 stderr:     self.bind_server_socket()
2024/08/05 20:13:18 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/05 20:13:18 stderr:     self.bind(sockaddr)
2024/08/05 20:13:18 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/05 20:13:18 stderr:     return self.socket.bind(addr)
2024/08/05 20:13:18 stderr: OSError: [Errno 98] Address in use
2024/08/05 20:13:18 Forked function has terminated: exit status 1
2024/08/05 20:13:19 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/05 20:13:19 Forking: python, arguments: [index.py]
2024/08/05 20:13:19 Started logging: stderr from function.
2024/08/05 20:13:19 Started logging: stdout from function.
2024/08/05 20:13:19 Watchdog mode: http	fprocess: "python index.py"
2024/08/05 20:13:19 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/05 20:13:19 Listening on port: 8080
2024/08/05 20:13:19 Writing lock-file to: /tmp/.lock
2024/08/05 20:13:19 Metrics listening on port: 8081
2024/08/05 20:13:19 stderr: Traceback (most recent call last):
2024/08/05 20:13:19 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/05 20:13:19 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/05 20:13:19 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/05 20:13:19 stderr:     server = _server(app, **kw)
2024/08/05 20:13:19 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/05 20:13:19 stderr:     last_serv = TcpWSGIServer(
2024/08/05 20:13:19 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/05 20:13:19 stderr:     self.bind_server_socket()
2024/08/05 20:13:19 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/05 20:13:19 stderr:     self.bind(sockaddr)
2024/08/05 20:13:19 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/05 20:13:19 stderr:     return self.socket.bind(addr)
2024/08/05 20:13:19 stderr: OSError: [Errno 98] Address in use
2024/08/05 20:13:19 Forked function has terminated: exit status 1
2024/08/05 20:13:21 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/05 20:13:21 Forking: python, arguments: [index.py]
2024/08/05 20:13:21 Started logging: stderr from function.
2024/08/05 20:13:21 Started logging: stdout from function.
2024/08/05 20:13:21 Watchdog mode: http	fprocess: "python index.py"
2024/08/05 20:13:21 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/05 20:13:21 Listening on port: 8080
2024/08/05 20:13:21 Writing lock-file to: /tmp/.lock
2024/08/05 20:13:21 Metrics listening on port: 8081
2024/08/05 20:13:21 stderr: Traceback (most recent call last):
2024/08/05 20:13:21 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/05 20:13:21 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/05 20:13:21 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/05 20:13:21 stderr:     server = _server(app, **kw)
2024/08/05 20:13:21 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/05 20:13:21 stderr:     last_serv = TcpWSGIServer(
2024/08/05 20:13:21 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/05 20:13:21 stderr:     self.bind_server_socket()
2024/08/05 20:13:21 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/05 20:13:21 stderr:     self.bind(sockaddr)
2024/08/05 20:13:21 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/05 20:13:21 stderr:     return self.socket.bind(addr)
2024/08/05 20:13:21 stderr: OSError: [Errno 98] Address in use
2024/08/05 20:13:21 Forked function has terminated: exit status 1

**Comment by sauloapp** [comment]
Is it possible to customize faas port, @levisingularity ?

**Comment by levisingularity** [comment]
@sauloapp Unfortunately not yet, but It is something to be done. If there is another user running a different version of faas on the same machine, this might be the reason for this issue.

**Comment by sauloapp** [comment]
@levisingularity look t  this, please: I started  openfaas and it exited before any connection:

 nice_moore
saulo@dl:/mnt/hdd_2/saulo/snet/rejuve.bio/das/shared_rep/data$ docker ps -a
CONTAINER ID   IMAGE                                  COMMAND                  CREATED          STATUS                      PORTS                                           NAMES
3e0d7a9a1ef1   trueagi/openfaas:query-engine-latest   "fwatchdog"              27 seconds ago   Exited (1) 19 seconds ago                                                   das-cli-openfaas-8080

**Comment by levisingularity** [comment]
@sauloapp I suppose It might be closing because it cannot be connected to the port

Can you run `docker logs das-cli-openfaas-8080`?

**Comment by sauloapp** [comment]
@levisingularity it seems to be equal:
faas-8080
2024/08/06 18:21:44 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/06 18:21:44 Forking: python, arguments: [index.py]
2024/08/06 18:21:44 Started logging: stderr from function.
2024/08/06 18:21:44 Started logging: stdout from function.
2024/08/06 18:21:44 Watchdog mode: http	fprocess: "python index.py"
2024/08/06 18:21:44 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/06 18:21:44 Listening on port: 8080
2024/08/06 18:21:44 Writing lock-file to: /tmp/.lock
2024/08/06 18:21:44 Metrics listening on port: 8081
2024/08/06 18:21:44 stderr: Traceback (most recent call last):
2024/08/06 18:21:44 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/06 18:21:44 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/06 18:21:44 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/06 18:21:44 stderr:     server = _server(app, **kw)
2024/08/06 18:21:44 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/06 18:21:44 stderr:     last_serv = TcpWSGIServer(
2024/08/06 18:21:44 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/06 18:21:44 stderr:     self.bind_server_socket()
2024/08/06 18:21:44 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/06 18:21:44 stderr:     self.bind(sockaddr)
2024/08/06 18:21:44 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/06 18:21:44 stderr:     return self.socket.bind(addr)
2024/08/06 18:21:44 stderr: OSError: [Errno 98] Address in use
2024/08/06 18:21:44 Forked function has terminated: exit status 1
2024/08/06 18:21:45 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/06 18:21:45 Forking: python, arguments: [index.py]
2024/08/06 18:21:45 Started logging: stderr from function.
2024/08/06 18:21:45 Started logging: stdout from function.
2024/08/06 18:21:45 Watchdog mode: http	fprocess: "python index.py"
2024/08/06 18:21:45 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/06 18:21:45 Listening on port: 8080
2024/08/06 18:21:45 Writing lock-file to: /tmp/.lock
2024/08/06 18:21:45 Metrics listening on port: 8081
2024/08/06 18:21:45 stderr: Traceback (most recent call last):
2024/08/06 18:21:45 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/06 18:21:45 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/06 18:21:45 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/06 18:21:45 stderr:     server = _server(app, **kw)
2024/08/06 18:21:45 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/06 18:21:45 stderr:     last_serv = TcpWSGIServer(
2024/08/06 18:21:45 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/06 18:21:45 stderr:     self.bind_server_socket()
2024/08/06 18:21:45 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/06 18:21:45 stderr:     self.bind(sockaddr)
2024/08/06 18:21:45 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/06 18:21:45 stderr:     return self.socket.bind(addr)
2024/08/06 18:21:45 stderr: OSError: [Errno 98] Address in use
2024/08/06 18:21:45 Forked function has terminated: exit status 1
2024/08/06 18:21:46 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/06 18:21:46 Forking: python, arguments: [index.py]
2024/08/06 18:21:46 Started logging: stderr from function.
2024/08/06 18:21:46 Started logging: stdout from function.
2024/08/06 18:21:46 Watchdog mode: http	fprocess: "python index.py"
2024/08/06 18:21:46 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/06 18:21:46 Listening on port: 8080
2024/08/06 18:21:46 Writing lock-file to: /tmp/.lock
2024/08/06 18:21:46 Metrics listening on port: 8081
2024/08/06 18:21:46 stderr: Traceback (most recent call last):
2024/08/06 18:21:46 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/06 18:21:46 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/06 18:21:46 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/06 18:21:46 stderr:     server = _server(app, **kw)
2024/08/06 18:21:46 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/06 18:21:46 stderr:     last_serv = TcpWSGIServer(
2024/08/06 18:21:46 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/06 18:21:46 stderr:     self.bind_server_socket()
2024/08/06 18:21:46 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/06 18:21:46 stderr:     self.bind(sockaddr)
2024/08/06 18:21:46 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/06 18:21:46 stderr:     return self.socket.bind(addr)
2024/08/06 18:21:46 stderr: OSError: [Errno 98] Address in use
2024/08/06 18:21:46 Forked function has terminated: exit status 1
2024/08/06 18:21:47 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/06 18:21:47 Forking: python, arguments: [index.py]
2024/08/06 18:21:47 Started logging: stderr from function.
2024/08/06 18:21:47 Started logging: stdout from function.
2024/08/06 18:21:47 Watchdog mode: http	fprocess: "python index.py"
2024/08/06 18:21:47 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/06 18:21:47 Listening on port: 8080
2024/08/06 18:21:47 Writing lock-file to: /tmp/.lock
2024/08/06 18:21:47 Metrics listening on port: 8081
2024/08/06 18:21:47 stderr: Traceback (most recent call last):
2024/08/06 18:21:47 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/06 18:21:47 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/06 18:21:47 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/06 18:21:47 stderr:     server = _server(app, **kw)
2024/08/06 18:21:47 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/06 18:21:47 stderr:     last_serv = TcpWSGIServer(
2024/08/06 18:21:47 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/06 18:21:47 stderr:     self.bind_server_socket()
2024/08/06 18:21:47 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/06 18:21:47 stderr:     self.bind(sockaddr)
2024/08/06 18:21:47 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/06 18:21:47 stderr:     return self.socket.bind(addr)
2024/08/06 18:21:47 stderr: OSError: [Errno 98] Address in use
2024/08/06 18:21:47 Forked function has terminated: exit status 1
2024/08/06 18:21:48 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/06 18:21:48 Forking: python, arguments: [index.py]
2024/08/06 18:21:48 Started logging: stderr from function.
2024/08/06 18:21:48 Started logging: stdout from function.
2024/08/06 18:21:48 Watchdog mode: http	fprocess: "python index.py"
2024/08/06 18:21:48 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/06 18:21:48 Listening on port: 8080
2024/08/06 18:21:48 Writing lock-file to: /tmp/.lock
2024/08/06 18:21:48 Metrics listening on port: 8081
2024/08/06 18:21:49 stderr: Traceback (most recent call last):
2024/08/06 18:21:49 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/06 18:21:49 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/06 18:21:49 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/06 18:21:49 stderr:     server = _server(app, **kw)
2024/08/06 18:21:49 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/06 18:21:49 stderr:     last_serv = TcpWSGIServer(
2024/08/06 18:21:49 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/06 18:21:49 stderr:     self.bind_server_socket()
2024/08/06 18:21:49 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/06 18:21:49 stderr:     self.bind(sockaddr)
2024/08/06 18:21:49 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/06 18:21:49 stderr:     return self.socket.bind(addr)
2024/08/06 18:21:49 stderr: OSError: [Errno 98] Address in use
2024/08/06 18:21:49 Forked function has terminated: exit status 1
2024/08/06 18:21:50 Version: 0.9.10	SHA: eefeb9dd8c979398a46fc0decc3297591362bfab
2024/08/06 18:21:50 Forking: python, arguments: [index.py]
2024/08/06 18:21:50 Started logging: stderr from function.
2024/08/06 18:21:50 Started logging: stdout from function.
2024/08/06 18:21:50 Watchdog mode: http	fprocess: "python index.py"
2024/08/06 18:21:50 Timeouts: read: 30m0s write: 30m0s hard: 30m0s health: 30m0s
2024/08/06 18:21:50 Listening on port: 8080
2024/08/06 18:21:50 Writing lock-file to: /tmp/.lock
2024/08/06 18:21:50 Metrics listening on port: 8081
2024/08/06 18:21:51 stderr: Traceback (most recent call last):
2024/08/06 18:21:51 stderr:   File "/home/app/index.py", line 109, in <module>
2024/08/06 18:21:51 stderr:     serve(app, host="0.0.0.0", port=5000)
2024/08/06 18:21:51 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 13, in serve
2024/08/06 18:21:51 stderr:     server = _server(app, **kw)
2024/08/06 18:21:51 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
2024/08/06 18:21:51 stderr:     last_serv = TcpWSGIServer(
2024/08/06 18:21:51 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 243, in __init__
2024/08/06 18:21:51 stderr:     self.bind_server_socket()
2024/08/06 18:21:51 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 364, in bind_server_socket
2024/08/06 18:21:51 stderr:     self.bind(sockaddr)
2024/08/06 18:21:51 stderr:   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 395, in bind
2024/08/06 18:21:51 stderr:     return self.socket.bind(addr)
2024/08/06 18:21:51 stderr: OSError: [Errno 98] Address in use
2024/08/06 18:21:51 Forked function has terminated: exit status 1

**Comment by levisingularity** [comment]
@sauloapp  Can you close the port 8080 to be available for connection?
