### ISSUE TITLE
DAS API page is broken

### ISSUE THREAD

**Issue by andre-senna** [singnet/das#70]
When hiting https://singnet.github.io/das-query-engine/api/das/  I see gigantic icons followed by a 404 error.

So we have 2 problems which need to be fixed in this card:

* (1) 404 page should NOT show those gigantic icons
* (2) The API documentation is either not being built or is being deployed somewhere else (if that's the case, the link in our main documentation hub (README in `das` repo) should be fixed.

**Comment by levisingularity** [comment]
This is the right url: https://singnet.github.io/das-query-engine/api/DAS/

**Comment by levisingularity** [comment]
I've also moved the docs from the query engine to das

https://github.com/singnet/das-query-engine/pull/312
https://github.com/singnet/das/pull/76

**Comment by levisingularity** [comment]
Link on README.md was fixed
